permissions:
  contents: read
name: run-ci-tests
on: [push, pull_request, workflow_dispatch]
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: ^3.8
      - uses: pre-commit/action@v3.0.0
  run-unit-tests:
    runs-on: ubuntu-latest
    env:
      MYSQL_USERNAME: secretsmanager_test
      MYSQL_PASSWORD: Password123!
      POSTGRESQL_USERNAME: secretsmanager_test
      POSTGRESQL_PASSWORD: Password123!
    steps:
        uses: actions/checkout@v4.1.1
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ^3.8
          cache: 'pip'
      - name: Install dependencies
        run: python -m pip install -r requirements-dev.txt .
      - name: Setup MySQL
        run: |
          sudo systemctl start mysql
          mysql -u root -p"root" -e "CREATE USER '$MYSQL_USERNAME'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';"
          mysql -u root -p"root" -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USERNAME'@'localhost' WITH GRANT OPTION;"
          mysql -u root -p"root" -e "FLUSH PRIVILEGES;"
          mysql -u root -p"root" -e "CREATE DATABASE mysql_secretsmanager_test CHARACTER SET utf8;"
      - name: Setup Postgresql
        run: |
          sudo cp tests/sample_pg_hba.conf /etc/postgresql/*/main/pg_hba.conf
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE USER $POSTGRESQL_USERNAME WITH PASSWORD '$POSTGRESQL_PASSWORD';"
          sudo -u postgres psql -c "ALTER USER $POSTGRESQL_USERNAME WITH SUPERUSER;"
          sudo -u postgres psql -c "CREATE DATABASE postgresql_secretsmanager_test ENCODING 'UTF8';"
      - name: Run database migrations
        run: cd tests/ && /bin/bash migrate_all_databases.sh
      - name: Run unit tests
        run: cd tests/ && /bin/bash run_all_tests.sh
